### ISSUE TITLE
Fields using zoom.component.compose appear to have a dependency on an "instance"

### ISSUE THREAD

**Issue by sean-hayes** [dsilabs/zoom#12]
I have not looked into specifically what "instance" is, but something like this works on the web and fails from tests or the command line:

    from zoom.fields import PulldownField
    f = PulldownField('Type', options=[('',''),('One',1),('Two',2)])
    f.edit()

error is:
AttributeError: '_thread._local' object has no attribute 'parts'

**Comment by hlainchb** [comment]
Thanks.
