### ISSUE TITLE
Binary responses fail where it looks like a middleware(s) expects to be working on stings yet the content is bytes

### ISSUE THREAD

**Issue by sean-hayes** [dsilabs/zoom#13]
since commit 7d1dca39521fe87a592f4af40bf8646bcf4a94dc a view with this fails:

    def thumb(self):
        """test"""
        import os
        filename = os.path.abspath('activity.png')
        image = open(filename, 'rb').read()
        response = Response(image)
        response.headers['Content-type'] = 'image/png'
        return response (edited)

**Comment by hlainchb** [comment]
I believe this is resolved now.  Can you please check to see if it fixes the issue you were seeing?

**Comment by sean-hayes** [comment]
Yes, it is corrected in my example.
